---
name: slint-lsp
description: A LSP Server that adds features like auto-complete and live preview of the .slint files to many editors.
homepage: https://slint-ui.com/
licenses:
  - proprietary
  - GPL-3.0-or-later
languages:
  - Slint
categories:
  - LSP

source:
  id: pkg:cargo/slint@v1.3.2

bin:
  slint-lsp: "cargo:slint-lsp"
